#!/usr/bin/env python
# -*- Coding: UTF-8 -*-
"""
The Pipeline Data Base Model for pyDAL.
"""
from pydal import Field, DAL
from config import DB_NAME, DB_USER_NAME, DB_PASSWORD, DB_ADDRESS


db = DAL('mysql://{0}:{1}@{2}/{3}'.format(DB_USER_NAME,
                                          DB_PASSWORD,
                                          DB_ADDRESS,
                                          DB_NAME), check_reserved=False)


db.define_table('AstromParam',
	Field('DISTORT_DEGREES', type = 'integer' , length = 3 ),
	Field('CROSSID_RADIUS', type = 'decimal' ),
	Field('SN_THRESHOLDS', type = 'string' , length = 12 ),
	Field('FWHM_THRESHOLDS', type = 'string' , length = 8 ),
	Field('ASTREF_CATALOG', type = 'string' , length = 12 ),
	Field('ASTREFMAG_KEY', type = 'string' , length = 8 ),
	Field('ASTREFMAG_LIMITS', type = 'string' , length = 12 ),
	Field('MATCH_RESOL', type = 'integer' , length = 4 ),
	Field('POSITION_MAXERR', type = 'decimal' ),
	migrate = False)

db.define_table('ColdPixParam',
	Field('BPMask_ID', type = 'mediumint' , length = 8 ),
	Field('LOWTHRES', type = 'decimal' ),
	Field('HIGHTHRES', type = 'decimal' ),
	Field('FILTERSIZE', type = 'integer' , length = 3 ),
	migrate = False)

db.define_table('HotPixParam',
	Field('BPMask_ID', type = 'mediumint' , length = 8 ),
	Field('MAXITE', type = 'integer' , length = 3 ),
	Field('SIGMA', type = 'decimal' ),
	migrate = False)

db.define_table('NightFLATPerformance',
	Field('NIGHT', type = 'date' ),
	Field('ValidFlatExpRate', type = 'decimal' ),
	Field('ValidFlatFrameRate', type = 'decimal' ),
	Field('sumofexp', type = 'decimal' ),
	Field('sumofvalidexp', type = 'decimal' ),
	Field('NumberofFLATFrames', type = 'bigint' , length = 21 ),
	Field('NumberofValidFLATFrames', type = 'bigint' , length = 21 ),
	migrate = False)

db.define_table('NightPerformance',
	Field('NIGHT', type = 'date' ),
	Field('ValidExpRate', type = 'decimal' ),
	Field('ValidFrameRate', type = 'decimal' ),
	Field('sumofexp', type = 'decimal' ),
	Field('sumofvalidexp', type = 'decimal' ),
	Field('NumberofSCIEFrames', type = 'bigint' , length = 21 ),
	Field('NumberofValidSCIEFrames', type = 'bigint' , length = 21 ),
	migrate = False)

db.define_table('astromsol',
	Field('CRVAL1', type = 'double' ),
	Field('CRVAL2', type = 'double' ),
	Field('CRPIX1', type = 'double' ),
	Field('CRPIX2', type = 'double' ),
	Field('CD1_1', type = 'double' ),
	Field('CD1_2', type = 'double' ),
	Field('CD2_1', type = 'double' ),
	Field('CD2_2', type = 'double' ),
	Field('PV1_0', type = 'double' ),
	Field('PV1_1', type = 'double' ),
	Field('PV1_2', type = 'double' ),
	Field('PV1_4', type = 'double' ),
	Field('PV1_5', type = 'double' ),
	Field('PV1_6', type = 'double' ),
	Field('PV1_7', type = 'double' ),
	Field('PV1_8', type = 'double' ),
	Field('PV1_9', type = 'double' ),
	Field('PV1_10', type = 'double' ),
	Field('PV1_12', type = 'double' ),
	Field('PV1_13', type = 'double' ),
	Field('PV1_14', type = 'double' ),
	Field('PV1_15', type = 'double' ),
	Field('PV1_16', type = 'double' ),
	Field('PV2_0', type = 'double' ),
	Field('PV2_1', type = 'double' ),
	Field('PV2_2', type = 'double' ),
	Field('PV2_4', type = 'double' ),
	Field('PV2_5', type = 'double' ),
	Field('PV2_6', type = 'double' ),
	Field('PV2_7', type = 'double' ),
	Field('PV2_8', type = 'double' ),
	Field('PV2_9', type = 'double' ),
	Field('PV2_10', type = 'double' ),
	Field('PV2_12', type = 'double' ),
	Field('PV2_13', type = 'double' ),
	Field('PV2_14', type = 'double' ),
	Field('PV2_15', type = 'double' ),
	Field('PV2_16', type = 'double' ),
	Field('FGROUPNO', type = 'double' ),
	Field('ASTIRMS1', type = 'double' ),
	Field('ASTIRMS2', type = 'double' ),
	Field('ASTRRMS1', type = 'double' ),
	Field('ASTRRMS2', type = 'double' ),
	Field('ASTRNOBJ', type = 'integer' , length = 11 ),
	Field('ASTRLCHI', type = 'float' ),
	Field('ASTRNHOB', type = 'integer' , length = 11 ),
	Field('ASTRHCHI', type = 'float' ),
	Field('INSERTDATE_ASTR', type = 'timestamp' ),
	migrate = False)

db.define_table('bpmask',
	Field('Name', type = 'string' , length = 55 ),
	Field('CF_ID', type = 'mediumint' , length = 8 ),
	Field('MType_ID', type = 'integer' , length = 3 ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	Field('NBADPIX', type = 'integer' , length = 11 ),
	Field('is_valid', type = 'integer' , length = 3 ),
	Field('UserComment', type = 'text' ),
	Field('Quality_FLAG', type = 'integer' , length = 3 ),
	migrate = False)

db.define_table('calib_depth_procedures',
	Field('description', type = 'string' , length = 45 ),
	Field('acronynm', type = 'string' , length = 10 ),
	migrate = False)

db.define_table('calib_depth_rc',
	Field('id_rc', type = 'mediumint' , length = 8 ),
	Field('completeness_25', type = 'float' ),
	Field('completeness_50', type = 'float' ),
	Field('completeness_75', type = 'float' ),
	Field('depth_procedure', type = 'string' , length = 45 ),
	Field('timestamp', type = 'timestamp' ),
	migrate = False)

db.define_table('calib_depth_tiles',
	Field('id_tilesinfo', type = 'mediumint' , length = 8 ),
	Field('completeness_25', type = 'float' ),
	Field('completeness_50', type = 'float' ),
	Field('completeness_75', type = 'float' ),
	Field('depth_procedure', type = 'integer' , length = 3 ),
	Field('timestamp', type = 'timestamp' ),
	migrate = False)

db.define_table('calib_kext_rc',
	Field('id_rc', type = 'mediumint' , length = 8 ),
	Field('kext', type = 'float' ),
	Field('err_kext', type = 'float' ),
	Field('calib_procedure', type = 'integer' , length = 2 ),
	Field('id_calib_zp_system', type = 'mediumint' , length = 8 ),
	Field('id_calib_sss_calibration', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('calib_rc_crosscalib',
	Field('id_rc', type = 'mediumint' , length = 8 ),
	Field('id_rc_refframe', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('calib_sss_calibration',
	Field('valid_after', type = 'timestamp' ),
	Field('valid_before', type = 'timestamp' ),
	Field('id_sss_synth_phot', type = 'smallint' , length = 5 ),
	Field('band', type = 'char' , length = 5 ),
	Field('ext_coeff', type = 'decimal' ),
	Field('err_ext_coeff', type = 'decimal' ),
	Field('zp', type = 'decimal' ),
	Field('err_zp', type = 'decimal' ),
	Field('qflag', type = 'integer' , length = 11 ),
	migrate = False)

db.define_table('calib_sss_info',
	Field('sesame_name', type = 'char' , length = 20 ),
	Field('tycho_id', type = 'char' , length = 15 ),
	Field('oaj_name', type = 'char' , length = 45 ),
	Field('ra_j2000', type = 'decimal' ),
	Field('dec_j2000', type = 'decimal' ),
	Field('delta_ra', type = 'decimal' ),
	Field('delta_dec', type = 'decimal' ),
	Field('is_sss', type = 'integer' , length = 1 ),
	migrate = False)

db.define_table('calib_sss_spectra',
	Field('id_sss_info', type = 'smallint' , length = 5 ),
	Field('spectrum_file', type = 'string' , length = 150 ),
	migrate = False)

db.define_table('calib_sss_synth_phot',
	Field('id_sss_info', type = 'smallint' , length = 5 ),
	Field('id_sss_spectra', type = 'smallint' , length = 5 ),
	Field('id_transmission', type = 'smallint' , length = 5 ),
	Field('band', type = 'char' , length = 5 ),
	Field('mag_AB', type = 'decimal' ),
	Field('valid_after', type = 'timestamp' ),
	Field('valid_before', type = 'timestamp' ),
	migrate = False)

db.define_table('calib_zp_flags_descr',
	Field('bit', type = 'bit' , length = 16 ),
	Field('description', type = 'text' ),
	migrate = False)

db.define_table('calib_zp_procedures',
	Field('description', type = 'text' ),
	Field('acronym', type = 'string' , length = 10 ),
	migrate = False)

db.define_table('calib_zp_rc',
	Field('id_rc', type = 'mediumint' , length = 8 ),
	Field('zp', type = 'float' ),
	Field('err_zp', type = 'float' ),
	Field('calib_procedure', type = 'integer' , length = 2 ),
	Field('reference_ZP', type = 'integer' , length = 1 ),
	Field('image_datasum', type = 'integer' , length = 10 ),
	Field('catalog_date', type = 'string' , length = 19 ),
	Field('id_calib_sss_calibration', type = 'mediumint' , length = 8 ),
	Field('timestamp', type = 'timestamp' ),
	migrate = False)

db.define_table('calib_zp_system',
	Field('filter_id', type = 'integer' , length = 3 ),
	Field('zp', type = 'float' ),
	Field('err_zp', type = 'float' ),
	Field('valid_after', type = 'datetime' ),
	Field('valid_before', type = 'datetime' ),
	Field('calib_procedure', type = 'integer' , length = 2 ),
	Field('comment', type = 'text' ),
	Field('valid', type = 'integer' , length = 1 ),
	migrate = False)

db.define_table('calib_zp_tiles',
	Field('id_tilesinfo', type = 'mediumint' , length = 8 ),
	Field('zp', type = 'float' ),
	Field('err_zp', type = 'float' ),
	Field('calib_procedure', type = 'integer' , length = 2 ),
	Field('reference_ZP', type = 'integer' , length = 1 ),
	Field('flags', type = 'bit' , length = 16 ),
	Field('image_datasum', type = 'integer' , length = 10 ),
	Field('catalog_date', type = 'string' , length = 19 ),
	Field('timestamp', type = 'timestamp' ),
	migrate = False)

db.define_table('ccdchip',
	Field('Name', type = 'string' , length = 15 ),
	Field('Manufacturer', type = 'string' , length = 20 ),
	Field('Model', type = 'string' , length = 15 ),
	Field('Serial', type = 'string' , length = 15 ),
	Field('XSize', type = 'string' , length = 15 ),
	Field('YSize', type = 'string' , length = 15 ),
	Field('PixelSize', type = 'float' ),
	Field('Channels', type = 'string' , length = 15 ),
	Field('QEfficiency', type = 'string' , length = 25 ),
	Field('HotPixelMap', type = 'string' , length = 25 ),
	Field('Notes', type = 'tinytext' ),
	migrate = False)

db.define_table('celestialref',
	Field('Catalogue', type = 'string' , length = 10 ),
	Field('Equinox', type = 'char' , length = 7 ),
	Field('Notes', type = 'tinytext' ),
	migrate = False)

db.define_table('cfcomb',
	Field('CFname', type = 'string' , length = 60 ),
	Field('NAMERED', type = 'string' , length = 55 ),
	migrate = False)

db.define_table('char_gain',
	Field('DATEUT_START', type = 'timestamp' ),
	Field('DATEUT_END', type = 'timestamp' ),
	Field('DATE_INSERT', type = 'timestamp' ),
	Field('ChipName_ID', type = 'integer' , length = 3 ),
	Field('RO_MODE', type = 'string' , length = 15 ),
	Field('IS_VALID', type = 'integer' , length = 3 ),
	Field('GAIN_01', type = 'float' ),
	Field('GAIN_02', type = 'float' ),
	Field('GAIN_03', type = 'float' ),
	Field('GAIN_04', type = 'float' ),
	Field('GAIN_05', type = 'float' ),
	Field('GAIN_06', type = 'float' ),
	Field('GAIN_07', type = 'float' ),
	Field('GAIN_08', type = 'float' ),
	Field('GAIN_09', type = 'float' ),
	Field('GAIN_10', type = 'float' ),
	Field('GAIN_11', type = 'float' ),
	Field('GAIN_12', type = 'float' ),
	Field('GAIN_13', type = 'float' ),
	Field('GAIN_14', type = 'float' ),
	Field('GAIN_15', type = 'float' ),
	Field('GAIN_16', type = 'float' ),
	Field('RON_E_01', type = 'float' ),
	Field('RON_E_02', type = 'float' ),
	Field('RON_E_03', type = 'float' ),
	Field('RON_E_04', type = 'float' ),
	Field('RON_E_05', type = 'float' ),
	Field('RON_E_06', type = 'float' ),
	Field('RON_E_07', type = 'float' ),
	Field('RON_E_08', type = 'float' ),
	Field('RON_E_09', type = 'float' ),
	Field('RON_E_10', type = 'float' ),
	Field('RON_E_11', type = 'float' ),
	Field('RON_E_12', type = 'float' ),
	Field('RON_E_13', type = 'float' ),
	Field('RON_E_14', type = 'float' ),
	Field('RON_E_15', type = 'float' ),
	Field('RON_E_16', type = 'float' ),
	Field('METHOD', type = 'string' , length = 15 ),
	Field('N_SIGCLIP', type = 'float' ),
	Field('TRIM_NORM_X0', type = 'float' ),
	Field('TRIM_NORM_Y0', type = 'float' ),
	Field('TRIM_NORM_X1', type = 'float' ),
	Field('TRIM_NORM_Y1', type = 'float' ),
	Field('JYPE_TAG', type = 'string' , length = 15 ),
	migrate = False)

db.define_table('char_gain_imgs',
	Field('gain_id', type = 'mediumint' , length = 8 ),
	Field('OA_ID', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('char_icmap',
	Field('ori_id', type = 'mediumint' , length = 8 ),
	Field('DATEUT_START', type = 'timestamp' ),
	Field('DATEUT_END', type = 'timestamp' ),
	Field('DATE_INSERT', type = 'timestamp' ),
	Field('ChipName_ID', type = 'integer' , length = 3 ),
	Field('RO_MODE', type = 'string' , length = 15 ),
	Field('FILTER_ID', type = 'mediumint' , length = 9 ),
	Field('IS_VALID', type = 'integer' , length = 3 ),
	Field('POLY_TYPE', type = 'string' , length = 15 ),
	Field('BASIS_ORDER', type = 'integer' , length = 3 ),
	Field('NSTARS', type = 'mediumint' , length = 9 ),
	Field('NPOINTINGS', type = 'mediumint' , length = 9 ),
	Field('SNR_THRESHOLD', type = 'float' ),
	Field('RED_CHISQ', type = 'float' ),
	Field('OBJECT', type = 'string' , length = 15 ),
	Field('RA_deg', type = 'float' ),
	Field('DEC_deg', type = 'float' ),
	Field('DITH_TYPE', type = 'string' , length = 15 ),
	Field('JYPE_TAG', type = 'string' , length = 15 ),
	migrate = False)

db.define_table('char_icmap_param',
	Field('icmap_id', type = 'mediumint' , length = 8 ),
	Field('DEGREE', type = 'integer' , length = 3 ),
	Field('VAL', type = 'float' ),
	Field('ERR', type = 'float' ),
	migrate = False)

db.define_table('char_linear',
	Field('ori_id', type = 'mediumint' , length = 8 ),
	Field('DATEUT_START', type = 'timestamp' ),
	Field('DATEUT_END', type = 'timestamp' ),
	Field('DATE_INSERT', type = 'timestamp' ),
	Field('ChipName_ID', type = 'integer' , length = 3 ),
	Field('RO_MODE', type = 'string' , length = 15 ),
	Field('IS_VALID', type = 'integer' , length = 3 ),
	Field('N_IMGS', type = 'mediumint' , length = 9 ),
	Field('RANGE_LINFIT_0', type = 'float' ),
	Field('RANGE_LINFIT_1', type = 'float' ),
	Field('RANGE_POLYFIT_0', type = 'float' ),
	Field('RANGE_POLYFIT_1', type = 'float' ),
	Field('METHOD', type = 'string' , length = 15 ),
	Field('N_SIGCLIP', type = 'float' ),
	Field('TRIM_NORM_X0', type = 'float' ),
	Field('TRIM_NORM_Y0', type = 'float' ),
	Field('TRIM_NORM_X1', type = 'float' ),
	Field('TRIM_NORM_Y1', type = 'float' ),
	Field('JYPE_TAG', type = 'string' , length = 15 ),
	migrate = False)

db.define_table('char_linear_param',
	Field('linear_id', type = 'mediumint' , length = 8 ),
	Field('AMP', type = 'integer' , length = 3 ),
	Field('RED_CHISQ_LINFIT', type = 'float' ),
	Field('RED_CHISQ_POLY1', type = 'float' ),
	Field('RED_CHISQ_POLY2', type = 'float' ),
	Field('PAR_LINFIT_0', type = 'float' ),
	Field('ERR_LINFIT_0', type = 'float' ),
	Field('PAR_LINFIT_1', type = 'float' ),
	Field('ERR_LINFIT_1', type = 'float' ),
	Field('PAR_POLY1_0', type = 'float' ),
	Field('ERR_POLY1_0', type = 'float' ),
	Field('PAR_POLY1_1', type = 'float' ),
	Field('ERR_POLY1_1', type = 'float' ),
	Field('PAR_POLY2_0', type = 'float' ),
	Field('ERR_POLY2_0', type = 'float' ),
	Field('PAR_POLY2_1', type = 'float' ),
	Field('ERR_POLY2_1', type = 'float' ),
	Field('PAR_POLY2_2', type = 'float' ),
	Field('ERR_POLY2_2', type = 'float' ),
	migrate = False)

db.define_table('char_ron_adu',
	Field('DATEUT_START', type = 'timestamp' ),
	Field('DATEUT_END', type = 'timestamp' ),
	Field('DATE_INSERT', type = 'timestamp' ),
	Field('ChipName_ID', type = 'integer' , length = 3 ),
	Field('RO_MODE', type = 'string' , length = 15 ),
	Field('IS_VALID', type = 'integer' , length = 3 ),
	Field('RON_ADU_01', type = 'float' ),
	Field('RON_ADU_02', type = 'float' ),
	Field('RON_ADU_03', type = 'float' ),
	Field('RON_ADU_04', type = 'float' ),
	Field('RON_ADU_05', type = 'float' ),
	Field('RON_ADU_06', type = 'float' ),
	Field('RON_ADU_07', type = 'float' ),
	Field('RON_ADU_08', type = 'float' ),
	Field('RON_ADU_09', type = 'float' ),
	Field('RON_ADU_10', type = 'float' ),
	Field('RON_ADU_11', type = 'float' ),
	Field('RON_ADU_12', type = 'float' ),
	Field('RON_ADU_13', type = 'float' ),
	Field('RON_ADU_14', type = 'float' ),
	Field('RON_ADU_15', type = 'float' ),
	Field('RON_ADU_16', type = 'float' ),
	Field('METHOD', type = 'string' , length = 15 ),
	Field('N_SIGCLIP', type = 'float' ),
	Field('JYPE_TAG', type = 'string' , length = 15 ),
	migrate = False)

db.define_table('char_ron_adu_imgs',
	Field('ron_adu_id', type = 'mediumint' , length = 8 ),
	Field('OA_ID', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('corrected_all',
	Field('Name', type = 'char' , length = 55 ),
	Field('FRAMETYPE', type = 'string' , length = 10 ),
	Field('RA', type = 'decimal' ),
	Field('DEC', type = 'decimal' ),
	Field('FILTERNAME', type = 'string' , length = 15 ),
	Field('CORRDONE', type = 'smallint' , length = 6 ),
	Field('BIASFILE_ID', type = 'mediumint' , length = 8 ),
	Field('FLATFILE_ID', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('filter',
	Field('Name', type = 'string' , length = 15 ),
	Field('Wavelength', type = 'smallint' , length = 6 ),
	Field('Width', type = 'smallint' , length = 6 ),
	Field('Profile', type = 'string' , length = 25 ),
	Field('Manufacturer', type = 'string' , length = 20 ),
	Field('Model', type = 'string' , length = 15 ),
	Field('Serial', type = 'string' , length = 15 ),
	Field('Notes', type = 'tinytext' ),
	Field('ShortName', type = 'string' , length = 20 ),
	migrate = False)

db.define_table('frametype',
	Field('Name', type = 'string' , length = 10 ),
	Field('Notes', type = 'tinytext' ),
	migrate = False)

db.define_table('numberofflatframes',
	Field('NIGHT', type = 'date' ),
	Field('NumberofFLATFrames', type = 'bigint' , length = 21 ),
	Field('sumofexp', type = 'decimal' ),
	Field('DATEOBS', type = 'string' , length = 21 ),
	Field('IMGTYPE', type = 'string' , length = 10 ),
	migrate = False)

db.define_table('numberofscieframes',
	Field('NIGHT', type = 'date' ),
	Field('NumberofSCIEFrames', type = 'bigint' , length = 21 ),
	Field('sumofexp', type = 'decimal' ),
	Field('DATEOBS', type = 'string' , length = 21 ),
	Field('IMGTYPE', type = 'string' , length = 10 ),
	migrate = False)

db.define_table('numberofvalidflatframes',
	Field('NIGHT', type = 'date' ),
	Field('NumberofFLATFrames', type = 'bigint' , length = 21 ),
	Field('sumofexp', type = 'decimal' ),
	Field('DATEOBS', type = 'string' , length = 21 ),
	Field('IMGTYPE', type = 'string' , length = 10 ),
	migrate = False)

db.define_table('numberofvalidscieframes',
	Field('NIGHT', type = 'date' ),
	Field('NumberofSCIEFrames', type = 'bigint' , length = 21 ),
	Field('sumofexp', type = 'decimal' ),
	Field('DATEOBS', type = 'string' , length = 21 ),
	Field('IMGTYPE', type = 'string' , length = 10 ),
	migrate = False)

db.define_table('partialsurveyprogress',
	Field('partialtiles_id', type = 'integer' , length = 10 ),
	Field('TileName', type = 'string' , length = 45 ),
	Field('Astronomical_Night', type = 'date' ),
	Field('NImagsObs', type = 'integer' , length = 3 ),
	Field('NImagsObs_maxoverlap', type = 'integer' , length = 3 ),
	Field('NImagsGood', type = 'integer' , length = 3 ),
	Field('NImagsGood_maxoverlap', type = 'integer' , length = 3 ),
	Field('NImagsExitCorrect', type = 'integer' , length = 3 ),
	Field('NImagsExitCorrect_maxoverlap', type = 'integer' , length = 3 ),
	Field('Total_TExp', type = 'float' ),
	Field('Total_TExp_maxoverlap', type = 'float' ),
	Field('Used_TExp', type = 'float' ),
	Field('Used_TExp_maxoverlap', type = 'float' ),
	Field('Eff_TExp', type = 'float' ),
	Field('Eff_TExp_maxoverlap', type = 'float' ),
	Field('Flag', type = 'integer' , length = 3 ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	Field('ProCombinedHash', type = 'string' , length = 32 ),
	Field('RawCombinedHash', type = 'string' , length = 32 ),
	Field('RawFilteredHash', type = 'string' , length = 32 ),
	Field('ProFilteredHash', type = 'string' , length = 32 ),
	Field('ExitStatus', type = 'integer' , length = 3 ),
	Field('Update_timestamp', type = 'timestamp' ),
	migrate = False)

db.define_table('partialsurveyprogressepochview',
	Field('Tile_ID', type = 'integer' , length = 10 ),
	Field('partialsurveyprogress_id', type = 'mediumint' , length = 8 ),
	Field('partialtiles_id', type = 'integer' , length = 10 ),
	Field('Instrument_ID', type = 'integer' , length = 3 ),
	Field('Filter_ID', type = 'integer' , length = 3 ),
	Field('LogicalFilterName', type = 'string' , length = 20 ),
	Field('CCDChipId', type = 'integer' , length = 3 ),
	Field('TileName', type = 'string' , length = 45 ),
	Field('PRJ_ID', type = 'string' , length = 20 ),
	Field('regexpr', type = 'binary' , length = 0 ),
	Field('ReqExpTime', type = 'float' ),
	Field('ReqFWHM', type = 'float' ),
	Field('ReqTransparency', type = 'float' ),
	Field('ReqAirmass', type = 'float' ),
	Field('ReqOverlap', type = 'float' ),
	Field('OtherReq', type = 'text' ),
	Field('NReqExpos', type = 'integer' , length = 3 ),
	Field('IReqExpTime', type = 'float' ),
	Field('NImagsObs', type = 'integer' , length = 3 ),
	Field('NImagsObs_maxoverlap', type = 'integer' , length = 3 ),
	Field('NImagsGood', type = 'integer' , length = 3 ),
	Field('NImagsGood_maxoverlap', type = 'integer' , length = 3 ),
	Field('NImagsExitCorrect', type = 'integer' , length = 3 ),
	Field('NImagsExitCorrect_maxoverlap', type = 'integer' , length = 3 ),
	Field('Total_TExp', type = 'float' ),
	Field('Total_TExp_maxoverlap', type = 'float' ),
	Field('Used_TExp', type = 'float' ),
	Field('Used_TExp_maxoverlap', type = 'float' ),
	Field('Eff_TExp', type = 'float' ),
	Field('Eff_TExp_maxoverlap', type = 'float' ),
	Field('Flag', type = 'integer' , length = 3 ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	Field('ProCombinedHash', type = 'string' , length = 32 ),
	Field('RawCombinedHash', type = 'string' , length = 32 ),
	Field('RawFilteredHash', type = 'string' , length = 32 ),
	Field('ProFilteredHash', type = 'string' , length = 32 ),
	Field('ExitStatus', type = 'integer' , length = 3 ),
	Field('Update_timestamp', type = 'timestamp' ),
	Field('loadCatalog', type = 'mediumint' , length = 8 ),
	Field('astronomical_night', type = 'date' ),
	Field('epoch', type = 'bigint' , length = 22 ),
	migrate = False)

db.define_table('partialsurveyprogressview',
	Field('Tile_ID', type = 'integer' , length = 10 ),
	Field('Instrument_ID', type = 'integer' , length = 3 ),
	Field('Filter_ID', type = 'integer' , length = 3 ),
	Field('LogicalFilterName', type = 'string' , length = 20 ),
	Field('CCDChipId', type = 'integer' , length = 3 ),
	Field('TileName', type = 'string' , length = 45 ),
	Field('PRJ_ID', type = 'string' , length = 20 ),
	Field('regexpr', type = 'binary' , length = 0 ),
	Field('ReqExpTime', type = 'float' ),
	Field('ReqFWHM', type = 'float' ),
	Field('ReqTransparency', type = 'float' ),
	Field('ReqAirmass', type = 'float' ),
	Field('ReqOverlap', type = 'float' ),
	Field('OtherReq', type = 'text' ),
	Field('NReqExpos', type = 'integer' , length = 3 ),
	Field('IReqExpTime', type = 'float' ),
	Field('NImagsObs', type = 'integer' , length = 3 ),
	Field('NImagsObs_maxoverlap', type = 'integer' , length = 3 ),
	Field('NImagsGood', type = 'integer' , length = 3 ),
	Field('NImagsGood_maxoverlap', type = 'integer' , length = 3 ),
	Field('NImagsExitCorrect', type = 'integer' , length = 3 ),
	Field('NImagsExitCorrect_maxoverlap', type = 'integer' , length = 3 ),
	Field('Total_TExp', type = 'float' ),
	Field('Total_TExp_maxoverlap', type = 'float' ),
	Field('Used_TExp', type = 'float' ),
	Field('Used_TExp_maxoverlap', type = 'float' ),
	Field('Eff_TExp', type = 'float' ),
	Field('Eff_TExp_maxoverlap', type = 'float' ),
	Field('Flag', type = 'integer' , length = 3 ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	Field('ProCombinedHash', type = 'string' , length = 32 ),
	Field('RawCombinedHash', type = 'string' , length = 32 ),
	Field('RawFilteredHash', type = 'string' , length = 32 ),
	Field('ProFilteredHash', type = 'string' , length = 32 ),
	Field('ExitStatus', type = 'integer' , length = 3 ),
	Field('Update_timestamp', type = 'timestamp' ),
	Field('StartObservingDatetime', type = 'string' , length = 29 ),
	Field('EndObservingDatetime', type = 'string' , length = 29 ),
	Field('loadCatalog', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('partialtiles',
	Field('Tile_ID', type = 'integer' , length = 10 ),
	Field('Instrument_ID', type = 'integer' , length = 3 ),
	Field('Filter_ID', type = 'integer' , length = 3 ),
	Field('LogicalFilterName', type = 'string' , length = 20 ),
	Field('CCDChipId', type = 'integer' , length = 3 ),
	Field('TileName', type = 'string' , length = 45 ),
	Field('PRJ_ID', type = 'string' , length = 20 ),
	Field('ReqExpTime', type = 'float' ),
	Field('ReqFWHM', type = 'float' ),
	Field('ReqTransparency', type = 'float' ),
	Field('ReqAirmass', type = 'float' ),
	Field('ReqOverlap', type = 'float' ),
	Field('OtherReq', type = 'text' ),
	Field('NReqExpos', type = 'integer' , length = 3 ),
	Field('IReqExpTime', type = 'float' ),
	Field('StartObservingDatetime', type = 'datetime' ),
	Field('EndObservingDatetime', type = 'datetime' ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	Field('loadCatalog', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('pipeline',
	Field('Version', type = 'char' , length = 20 ),
	Field('TimeStamp', type = 'datetime' ),
	Field('Notes', type = 'tinytext' ),
	migrate = False)

db.define_table('proc_status',
	Field('ori_id', type = 'mediumint' , length = 8 ),
	Field('PROC_STATUS', type = 'integer' , length = 3 ),
	migrate = False)

db.define_table('proc_status_all',
	Field('Name', type = 'char' , length = 55 ),
	Field('FRAMETYPE', type = 'string' , length = 10 ),
	Field('RA', type = 'decimal' ),
	Field('DEC', type = 'decimal' ),
	Field('FILTERNAME', type = 'string' , length = 15 ),
	Field('CORRDONE', type = 'smallint' , length = 6 ),
	Field('BIASFILE_ID', type = 'mediumint' , length = 8 ),
	Field('FLATFILE_ID', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('proc_status_sci',
	Field('Name', type = 'char' , length = 55 ),
	Field('PRJ_ID', type = 'string' , length = 20 ),
	Field('PRJ_VER', type = 'string' , length = 20 ),
	Field('FILTERNAME', type = 'string' , length = 15 ),
	Field('FRAMETYPE', type = 'string' , length = 10 ),
	Field('Object', type = 'string' , length = 70 ),
	Field('ExpTime', type = 'decimal' ),
	Field('Date', type = 'date' ),
	Field('Time', type = 'time' ),
	Field('NIGHT', type = 'date' ),
	Field('RA', type = 'decimal' ),
	Field('DEC', type = 'decimal' ),
	Field('NAXIS1', type = 'smallint' , length = 6 ),
	Field('NAXIS2', type = 'smallint' , length = 6 ),
	Field('Overcode', type = 'string' , length = 16 ),
	Field('AirMass', type = 'decimal' ),
	Field('Observer', type = 'string' , length = 70 ),
	Field('Comment', type = 'string' , length = 70 ),
	Field('ADULevel', type = 'decimal' ),
	Field('DPRCATG', type = 'string' , length = 10 ),
	Field('DPRTYPE', type = 'string' , length = 10 ),
	Field('OBS_ID', type = 'string' , length = 30 ),
	Field('EXP_ID', type = 'string' , length = 30 ),
	Field('DATASUM', type = 'integer' , length = 10 ),
	Field('CHECKSUM', type = 'string' , length = 16 ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	Field('UPDATEDATE_OA', type = 'timestamp' ),
	Field('ImageType_ID', type = 'integer' , length = 3 ),
	Field('Filter_ID', type = 'integer' , length = 3 ),
	Field('is_valid', type = 'decimal' ),
	Field('UserComment', type = 'text' ),
	Field('Insert_Code', type = 'integer' , length = 3 ),
	Field('NAMERED', type = 'string' , length = 55 ),
	Field('Outdated', type = 'integer' , length = 1 ),
	Field('CFNotApplied', type = 'integer' , length = 1 ),
	Field('PROC_STATUS', type = 'integer' , length = 3 ),
	Field('CORREQUIRED', type = 'smallint' , length = 6 ),
	Field('CORRDONE', type = 'smallint' , length = 6 ),
	Field('INSERTDATE_RC', type = 'timestamp' ),
	Field('UPDATEDATE_RC', type = 'timestamp' ),
	Field('Exit_Status', type = 'smallint' , length = 5 ),
	Field('rc_id', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('qa_dualsingle',
	Field('tile_ID', type = 'mediumint' , length = 8 ),
	Field('ref_tile_ID', type = 'mediumint' , length = 8 ),
	Field('rms50', type = 'float' ),
	Field('rms10', type = 'float' ),
	Field('rms50sc', type = 'float' ),
	Field('rms10sc', type = 'float' ),
	Field('npoints10', type = 'float' ),
	Field('outpoints10', type = 'float' ),
	Field('npoints50', type = 'float' ),
	Field('outpoints50', type = 'float' ),
	Field('offset', type = 'float' ),
	migrate = False)

db.define_table('rc',
	Field('NAMERED', type = 'string' , length = 55 ),
	Field('PROC_VERSION', type = 'string' , length = 3 ),
	Field('ori_id', type = 'mediumint' , length = 8 ),
	Field('PROCMODE', type = 'integer' , length = 3 ),
	Field('Released', type = 'integer' , length = 3 ),
	Field('Outdated', type = 'integer' , length = 1 ),
	Field('ADULevel01', type = 'decimal' ),
	Field('ADULevel01_rms', type = 'decimal' ),
	Field('ADULevel02', type = 'decimal' ),
	Field('ADULevel02_rms', type = 'decimal' ),
	Field('ADULevel03', type = 'decimal' ),
	Field('ADULevel03_rms', type = 'decimal' ),
	Field('ADULevel04', type = 'decimal' ),
	Field('ADULevel04_rms', type = 'decimal' ),
	Field('ADULevel05', type = 'decimal' ),
	Field('ADULevel05_rms', type = 'decimal' ),
	Field('ADULevel06', type = 'decimal' ),
	Field('ADULevel06_rms', type = 'decimal' ),
	Field('ADULevel07', type = 'decimal' ),
	Field('ADULevel07_rms', type = 'decimal' ),
	Field('ADULevel08', type = 'decimal' ),
	Field('ADULevel08_rms', type = 'decimal' ),
	Field('ADULevel09', type = 'decimal' ),
	Field('ADULevel09_rms', type = 'decimal' ),
	Field('ADULevel10', type = 'decimal' ),
	Field('ADULevel10_rms', type = 'decimal' ),
	Field('ADULevel11', type = 'decimal' ),
	Field('ADULevel11_rms', type = 'decimal' ),
	Field('ADULevel12', type = 'decimal' ),
	Field('ADULevel12_rms', type = 'decimal' ),
	Field('ADULevel13', type = 'decimal' ),
	Field('ADULevel13_rms', type = 'decimal' ),
	Field('ADULevel14', type = 'decimal' ),
	Field('ADULevel14_rms', type = 'decimal' ),
	Field('ADULevel15', type = 'decimal' ),
	Field('ADULevel15_rms', type = 'decimal' ),
	Field('ADULevel16', type = 'decimal' ),
	Field('ADULevel16_rms', type = 'decimal' ),
	Field('NOISE01', type = 'decimal' ),
	Field('NOISE01_rms', type = 'decimal' ),
	Field('NOISE02', type = 'decimal' ),
	Field('NOISE02_rms', type = 'decimal' ),
	Field('NOISE03', type = 'decimal' ),
	Field('NOISE03_rms', type = 'decimal' ),
	Field('NOISE04', type = 'decimal' ),
	Field('NOISE04_rms', type = 'decimal' ),
	Field('NOISE05', type = 'decimal' ),
	Field('NOISE05_rms', type = 'decimal' ),
	Field('NOISE06', type = 'decimal' ),
	Field('NOISE06_rms', type = 'decimal' ),
	Field('NOISE07', type = 'decimal' ),
	Field('NOISE07_rms', type = 'decimal' ),
	Field('NOISE08', type = 'decimal' ),
	Field('NOISE08_rms', type = 'decimal' ),
	Field('NOISE09', type = 'decimal' ),
	Field('NOISE09_rms', type = 'decimal' ),
	Field('NOISE10', type = 'decimal' ),
	Field('NOISE10_rms', type = 'decimal' ),
	Field('NOISE11', type = 'decimal' ),
	Field('NOISE11_rms', type = 'decimal' ),
	Field('NOISE12', type = 'decimal' ),
	Field('NOISE12_rms', type = 'decimal' ),
	Field('NOISE13', type = 'decimal' ),
	Field('NOISE13_rms', type = 'decimal' ),
	Field('NOISE14', type = 'decimal' ),
	Field('NOISE14_rms', type = 'decimal' ),
	Field('NOISE15', type = 'decimal' ),
	Field('NOISE15_rms', type = 'decimal' ),
	Field('NOISE16', type = 'decimal' ),
	Field('NOISE16_rms', type = 'decimal' ),
	Field('FWHMG', type = 'decimal' ),
	Field('FWHMG_rms', type = 'decimal' ),
	Field('TRANSP_med', type = 'decimal' ),
	Field('TRANSP_mean', type = 'decimal' ),
	Field('TRANSP_rms', type = 'decimal' ),
	Field('nTRANScommonstars', type = 'mediumint' , length = 8 ),
	Field('nTRANScomputed', type = 'smallint' , length = 5 ),
	Field('TRANSP_ref', type = 'string' , length = 15 ),
	Field('ZPT1SEC', type = 'decimal' ),
	Field('ZPTQFLAG', type = 'integer' , length = 3 ),
	Field('NCOUNTS', type = 'integer' , length = 10 ),
	Field('SNNCOUTS', type = 'decimal' ),
	Field('CORRDONE', type = 'smallint' , length = 6 ),
	Field('CORREQUIRED', type = 'smallint' , length = 6 ),
	Field('CFNotApplied', type = 'integer' , length = 1 ),
	Field('Median_APERCOR', type = 'float' ),
	Field('Mean_APERCOR', type = 'float' ),
	Field('Std_APERCOR', type = 'float' ),
	Field('Number_APERCOR', type = 'integer' , length = 11 ),
	Field('InitNumber_APERCOR', type = 'integer' , length = 11 ),
	Field('Min_APERCOR', type = 'float' ),
	Field('Max_APERCOR', type = 'float' ),
	Field('init_aper_APERCOR', type = 'float' ),
	Field('full_aper_APERCOR', type = 'float' ),
	Field('NStars_Loaded_Total', type = 'float' ),
	Field('NStars_Accepted_Total', type = 'float' ),
	Field('FWHM_Mean', type = 'float' ),
	Field('FWHM_Min', type = 'float' ),
	Field('FWHM_Max', type = 'float' ),
	Field('MoffatBeta_Mean', type = 'float' ),
	Field('Ellipticity_Mean', type = 'float' ),
	Field('Asymmetry_Mean', type = 'float' ),
	Field('Chi2_Mean', type = 'float' ),
	Field('BIASFILE_ID', type = 'mediumint' , length = 8 ),
	Field('DARKFILE_ID', type = 'mediumint' , length = 8 ),
	Field('LINEFILE_ID', type = 'mediumint' , length = 8 ),
	Field('ICORFILE_ID', type = 'mediumint' , length = 8 ),
	Field('FLATFILE_ID', type = 'mediumint' , length = 8 ),
	Field('SFLAFILE_ID', type = 'mediumint' , length = 8 ),
	Field('PMAPFILE_ID', type = 'mediumint' , length = 8 ),
	Field('FRINFILE_ID', type = 'mediumint' , length = 8 ),
	Field('HOTPIXMASK_ID', type = 'mediumint' , length = 8 ),
	Field('COLDPIXMASK_ID', type = 'mediumint' , length = 8 ),
	Field('FRINGFAC', type = 'float' ),
	Field('DATASUM', type = 'integer' , length = 10 ),
	Field('CHECKSUM', type = 'string' , length = 16 ),
	Field('DATASUM_PREFIXPIX', type = 'integer' , length = 10 ),
	Field('MASKDATASUM', type = 'integer' , length = 10 ),
	Field('MASKCHECKSUM', type = 'string' , length = 16 ),
	Field('CATDATASUM', type = 'integer' , length = 10 ),
	Field('CATCHECKSUM', type = 'string' , length = 16 ),
	Field('NSatDetect', type = 'integer' , length = 3 ),
	Field('NCosmicRays', type = 'integer' , length = 10 ),
	Field('Quality_FLAG', type = 'integer' , length = 3 ),
	Field('is_valid', type = 'integer' , length = 3 ),
	Field('UserComment', type = 'text' ),
	Field('Exit_Status', type = 'smallint' , length = 5 ),
	Field('BlockExec', type = 'integer' , length = 3 ),
	Field('Comment', type = 'string' , length = 70 ),
	Field('UPDATEDATE_CR', type = 'timestamp' ),
	Field('INSERTDATE_CR', type = 'timestamp' ),
	Field('UPDATEDATE_CAT', type = 'timestamp' ),
	Field('Pipeline_ID', type = 'integer' , length = 3 ),
	Field('Release_ID', type = 'integer' , length = 3 ),
	Field('LOGFILE', type = 'string' , length = 15 ),
	Field('TimArrOper', type = 'smallint' , length = 5 ),
	Field('TimInitCat', type = 'smallint' , length = 5 ),
	Field('TimCrayDet', type = 'smallint' , length = 5 ),
	Field('TimSatDet', type = 'smallint' , length = 5 ),
	Field('TimBPM', type = 'smallint' , length = 5 ),
	Field('TimCorPix', type = 'smallint' , length = 5 ),
	Field('TimImgStat', type = 'smallint' , length = 5 ),
	Field('TimAstrRun', type = 'smallint' , length = 5 ),
	Field('TimProcCat', type = 'smallint' , length = 5 ),
	Field('TimCatOper', type = 'smallint' , length = 5 ),
	Field('TimAperCor', type = 'smallint' , length = 5 ),
	Field('TimRendImg', type = 'smallint' , length = 5 ),
	Field('TimPSFAnaly', type = 'smallint' , length = 5 ),
	Field('TimIOOut', type = 'smallint' , length = 5 ),
	Field('TimTotalPro', type = 'smallint' , length = 5 ),
	migrate = False)

db.define_table('rc_vignet',
	Field('RC_ID', type = 'mediumint' , length = 8 ),
	Field('nobjects', type = 'smallint' , length = 5 ),
	Field('ellipticity', type = 'float' ),
	Field('eccentricity', type = 'float' ),
	Field('orientation', type = 'float' ),
	migrate = False)

db.define_table('reduced2hpix',
	Field('hpix', type = 'integer' , length = 11 ),
	Field('image_id', type = 'integer' , length = 11 ),
	Field('filter_id', type = 'integer' , length = 11 ),
	migrate = False)

db.define_table('release',
	Field('Release', type = 'char' , length = 15 ),
	Field('TimeStamp', type = 'datetime' ),
	Field('Notes', type = 'tinytext' ),
	migrate = False)

db.define_table('starscalib',
	Field('ImageName', type = 'string' , length = 15 ),
	Field('NameOri', type = 'string' , length = 15 ),
	Field('ZPtResid', type = 'decimal' ),
	Field('ZPtResid_RMS', type = 'decimal' ),
	Field('XImage', type = 'decimal' ),
	Field('XImage_RMS', type = 'decimal' ),
	Field('YImage', type = 'decimal' ),
	Field('YImage_RMS', type = 'decimal' ),
	Field('RA', type = 'decimal' ),
	Field('RA_RMS', type = 'decimal' ),
	Field('DEC', type = 'decimal' ),
	Field('DEC_RMS', type = 'decimal' ),
	Field('RADECsys_ID', type = 'integer' , length = 3 ),
	Field('XFocal', type = 'decimal' ),
	Field('YFocal', type = 'decimal' ),
	migrate = False)

db.define_table('surveyprogress',
	Field('Tile_ID', type = 'integer' , length = 10 ),
	Field('Instrument_ID', type = 'integer' , length = 3 ),
	Field('Filter_ID', type = 'integer' , length = 3 ),
	Field('LogicalFilterName', type = 'string' , length = 20 ),
	Field('CCDChipId', type = 'integer' , length = 3 ),
	Field('TileName', type = 'string' , length = 50 ),
	Field('PRJ_ID', type = 'string' , length = 20 ),
	Field('regexpr', type = 'string' , length = 20 ),
	Field('ReqExpTime', type = 'float' ),
	Field('ReqFWHM', type = 'float' ),
	Field('ReqTransparency', type = 'float' ),
	Field('ReqAirmass', type = 'float' ),
	Field('ReqOverlap', type = 'float' ),
	Field('OtherReq', type = 'text' ),
	Field('NReqExpos', type = 'integer' , length = 3 ),
	Field('IReqExpTime', type = 'float' ),
	Field('NImagsObs', type = 'integer' , length = 3 ),
	Field('NImagsObs_maxoverlap', type = 'integer' , length = 3 ),
	Field('NImagsGood', type = 'integer' , length = 3 ),
	Field('NImagsGood_maxoverlap', type = 'integer' , length = 3 ),
	Field('NImagsExitCorrect', type = 'integer' , length = 3 ),
	Field('NImagsExitCorrect_maxoverlap', type = 'integer' , length = 3 ),
	Field('Total_TExp', type = 'float' ),
	Field('Total_TExp_maxoverlap', type = 'float' ),
	Field('Used_TExp', type = 'float' ),
	Field('Used_TExp_maxoverlap', type = 'float' ),
	Field('Eff_TExp', type = 'float' ),
	Field('Eff_TExp_maxoverlap', type = 'float' ),
	Field('Flag', type = 'integer' , length = 3 ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	Field('ProCombinedHash', type = 'string' , length = 32 ),
	Field('RawCombinedHash', type = 'string' , length = 32 ),
	Field('RawFilteredHash', type = 'string' , length = 32 ),
	Field('ProFilteredHash', type = 'string' , length = 32 ),
	Field('ExitStatus', type = 'integer' , length = 4 ),
	Field('Update_timestamp', type = 'timestamp' ),
	Field('StartObservingDatetime', type = 'datetime' ),
	Field('EndObservingDatetime', type = 'datetime' ),
	Field('loadCatalog', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('t80cfImgs',
	Field('CF_ID', type = 'mediumint' , length = 8 ),
	Field('RC_ID', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('t80cftab',
	Field('CFname', type = 'string' , length = 60 ),
	Field('CFtype_ID', type = 'integer' , length = 3 ),
	Field('PROC_VERSION', type = 'string' , length = 3 ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	Field('UPDATEDATE_CF', type = 'timestamp' ),
	Field('Telescope_ID', type = 'integer' , length = 3 ),
	Field('Instrument_ID', type = 'integer' , length = 3 ),
	Field('NCCD', type = 'integer' , length = 4 ),
	Field('ChipName_ID', type = 'integer' , length = 3 ),
	Field('ReadoutMode', type = 'string' , length = 10 ),
	Field('ReadoutSpeed', type = 'string' , length = 10 ),
	Field('ReadoutClock', type = 'string' , length = 30 ),
	Field('Overcode', type = 'string' , length = 16 ),
	Field('RunNameString', type = 'string' , length = 15 ),
	Field('ValRun_S', type = 'datetime' ),
	Field('ValRun_E', type = 'datetime' ),
	Field('Noise', type = 'decimal' ),
	Field('Noise_RMS', type = 'decimal' ),
	Field('ADULevel', type = 'decimal' ),
	Field('ADULevel_RMS', type = 'decimal' ),
	Field('NCombined', type = 'smallint' , length = 5 ),
	Field('NSelectedImgs', type = 'smallint' , length = 5 ),
	Field('NFilteredImgs', type = 'smallint' , length = 5 ),
	Field('Pipeline_ID', type = 'integer' , length = 3 ),
	Field('Release_ID', type = 'integer' , length = 3 ),
	Field('Filter_ID', type = 'integer' , length = 3 ),
	Field('is_valid', type = 'integer' , length = 3 ),
	Field('UserComment', type = 'text' ),
	Field('Quality_FLAG', type = 'integer' , length = 3 ),
	Field('DATASUM', type = 'integer' , length = 10 ),
	Field('CHECKSUM', type = 'string' , length = 16 ),
	Field('DATASUM_PREFIXPIX', type = 'integer' , length = 10 ),
	Field('Exit_Status', type = 'smallint' , length = 5 ),
	Field('BlockExec', type = 'integer' , length = 3 ),
	migrate = False)

db.define_table('t80instrument',
	Field('Name', type = 'string' , length = 15 ),
	Field('Telescope_ID', type = 'integer' , length = 3 ),
	Field('Notes', type = 'tinytext' ),
	migrate = False)

db.define_table('t80nighttab',
	Field('Date', type = 'date' ),
	Field('PhotoInterval_S', type = 'time' ),
	Field('PhotoInterval_E', type = 'time' ),
	Field('Instrument_ID', type = 'integer' , length = 3 ),
	Field('FilterName', type = 'string' , length = 10 ),
	Field('NCCD', type = 'integer' , length = 4 ),
	Field('ZPtFil', type = 'decimal' ),
	Field('ZPTFIL_RMS', type = 'decimal' ),
	Field('ExtCoeFil', type = 'decimal' ),
	Field('ExtCoeFil_RMS', type = 'decimal' ),
	Field('ExtCoeFil_EC', type = 'decimal' ),
	Field('ExtCoeFil_RMS_EC', type = 'decimal' ),
	Field('NightQA', type = 'integer' , length = 4 ),
	Field('NightQM', type = 'integer' , length = 4 ),
	migrate = False)

db.define_table('t80oa',
	Field('Name', type = 'char' , length = 55 ),
	Field('Origfile', type = 'char' , length = 55 ),
	Field('NAXIS1', type = 'smallint' , length = 6 ),
	Field('NAXIS2', type = 'smallint' , length = 6 ),
	Field('Overcode', type = 'string' , length = 16 ),
	Field('Date', type = 'date' ),
	Field('Time', type = 'time' ),
	Field('MJDobs', type = 'decimal' ),
	Field('UTC', type = 'decimal' ),
	Field('LST', type = 'decimal' ),
	Field('Telescope_ID', type = 'integer' , length = 3 ),
	Field('Instrument_ID', type = 'integer' , length = 3 ),
	Field('NCCD', type = 'integer' , length = 4 ),
	Field('ChipName_ID', type = 'integer' , length = 3 ),
	Field('RA', type = 'decimal' ),
	Field('DEC', type = 'decimal' ),
	Field('RADECsys_ID', type = 'integer' , length = 3 ),
	Field('AirMass', type = 'decimal' ),
	Field('Observer', type = 'string' , length = 70 ),
	Field('PRJ_ID', type = 'string' , length = 20 ),
	Field('PRJ_VER', type = 'string' , length = 20 ),
	Field('Comment', type = 'string' , length = 70 ),
	Field('Object', type = 'string' , length = 70 ),
	Field('ExpTime', type = 'decimal' ),
	Field('DewTemp', type = 'decimal' ),
	Field('CCDTemp', type = 'decimal' ),
	Field('DIMMFWHM', type = 'decimal' ),
	Field('OPACFWHM', type = 'decimal' ),
	Field('TEL_ELSTART', type = 'decimal' ),
	Field('TEL_ELEND', type = 'decimal' ),
	Field('TEL_AZSTART', type = 'decimal' ),
	Field('TEL_AZEND', type = 'decimal' ),
	Field('DOME_AZ', type = 'decimal' ),
	Field('TRAK_STATUS', type = 'string' , length = 15 ),
	Field('TEL_MIRRTEMP', type = 'float' ),
	Field('DOME_TEMP', type = 'float' ),
	Field('TEL_MIRRTEMP2', type = 'float' ),
	Field('TEL_POINT', type = 'string' , length = 10 ),
	Field('INS_TEMP', type = 'float' ),
	Field('AMBI_WINDSPDMEAN', type = 'float' ),
	Field('AMBI_WINDSPDRMS', type = 'float' ),
	Field('AMBI_WINDDIRMEAN', type = 'float' ),
	Field('AMBI_WINDRIDRMS', type = 'float' ),
	Field('AMBI_RHUMMEAN', type = 'float' ),
	Field('AMBI_RHUMRMS', type = 'float' ),
	Field('AMBI_PRESMEAN', type = 'float' ),
	Field('AMBI_PRERMS', type = 'float' ),
	Field('AMBI_TEMPMEAN', type = 'float' ),
	Field('AMBI_TEMPRMS', type = 'float' ),
	Field('HEXAPOD_X', type = 'float' ),
	Field('HEXAPOD_Y', type = 'float' ),
	Field('HEXAPOD_Z', type = 'float' ),
	Field('HEXAPOD_U', type = 'float' ),
	Field('HEXAPOD_V', type = 'float' ),
	Field('TUBE_ROD_TEMP', type = 'float' ),
	Field('ADULevel', type = 'decimal' ),
	Field('ADULevel_RMS', type = 'decimal' ),
	Field('Noise', type = 'decimal' ),
	Field('Noise_RMS', type = 'decimal' ),
	Field('DPRCATG', type = 'string' , length = 10 ),
	Field('DPRTYPE', type = 'string' , length = 10 ),
	Field('ReadoutMode', type = 'string' , length = 10 ),
	Field('ReadoutSpeed', type = 'string' , length = 10 ),
	Field('ReadoutClock', type = 'string' , length = 30 ),
	Field('OBS_ID', type = 'string' , length = 30 ),
	Field('EXP_ID', type = 'string' , length = 30 ),
	Field('DATASUM', type = 'integer' , length = 10 ),
	Field('CHECKSUM', type = 'string' , length = 16 ),
	Field('Quality_FLAG', type = 'integer' , length = 3 ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	Field('UPDATEDATE_OA', type = 'timestamp' ),
	Field('ImageType_ID', type = 'integer' , length = 3 ),
	Field('Filter_ID', type = 'integer' , length = 3 ),
	Field('is_valid', type = 'integer' , length = 3 ),
	Field('UserComment', type = 'text' ),
	Field('Insert_Code', type = 'integer' , length = 3 ),
	migrate = False)

db.define_table('t80tileImgs',
	Field('Tile_ID', type = 'mediumint' , length = 8 ),
	Field('RC_ID', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('t80tiles',
	Field('PName', type = 'string' , length = 30 ),
	Field('PRJ_ID', type = 'string' , length = 20 ),
	Field('PRJ_VER', type = 'string' , length = 20 ),
	Field('RA', type = 'double' ),
	Field('DEC', type = 'double' ),
	Field('RADECsys_ID', type = 'integer' , length = 3 ),
	Field('PIXEL_SCALE', type = 'double' ),
	Field('IMAGE_SIZE', type = 'mediumint' , length = 9 ),
	migrate = False)

db.define_table('t80tilescatalogs',
	Field('tile_ID', type = 'mediumint' , length = 8 ),
	Field('cat_type', type = 'smallint' , length = 3 ),
	Field('ref_tile_ID', type = 'mediumint' , length = 8 ),
	Field('cat_DATASUM', type = 'integer' , length = 10 ),
	Field('cat_CHECKSUM', type = 'string' , length = 16 ),
	Field('img_DATASUM', type = 'integer' , length = 10 ),
	Field('img_CHECKSUM', type = 'string' , length = 16 ),
	Field('ref_img_DATASUM', type = 'integer' , length = 10 ),
	Field('ref_img_CHECKSUM', type = 'string' , length = 16 ),
	Field('UPDATEDATE_CAT', type = 'timestamp' ),
	Field('numberobjects', type = 'integer' , length = 10 ),
	Field('update_date', type = 'timestamp' ),
	migrate = False)

db.define_table('t80tilesinfo',
	Field('Tile_ID', type = 'integer' , length = 10 ),
	Field('TileName', type = 'string' , length = 50 ),
	Field('PROCMODE', type = 'integer' , length = 3 ),
	Field('CFNotApplied', type = 'integer' , length = 1 ),
	Field('Released', type = 'integer' , length = 3 ),
	Field('Outdated', type = 'integer' , length = 1 ),
	Field('PROC_VERSION', type = 'string' , length = 3 ),
	Field('TILE_VERSION', type = 'string' , length = 3 ),
	Field('RefImage_ID', type = 'mediumint' , length = 8 ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	Field('UPDATEDATE_tile', type = 'timestamp' ),
	Field('Instrument_ID', type = 'integer' , length = 3 ),
	Field('Telescope_ID', type = 'integer' , length = 3 ),
	Field('NCCD', type = 'integer' , length = 4 ),
	Field('Noise', type = 'decimal' ),
	Field('Noise_RMS', type = 'decimal' ),
	Field('ADULevel', type = 'decimal' ),
	Field('ADULevel_RMS', type = 'decimal' ),
	Field('NCombined', type = 'smallint' , length = 5 ),
	Field('NSelectedImgs', type = 'smallint' , length = 5 ),
	Field('NFilteredImgs', type = 'smallint' , length = 5 ),
	Field('RawCombinedHash', type = 'string' , length = 32 ),
	Field('ProCombinedHash', type = 'string' , length = 32 ),
	Field('TExposed', type = 'decimal' ),
	Field('EfecTime', type = 'decimal' ),
	Field('ExpTime', type = 'decimal' ),
	Field('FWHMG', type = 'decimal' ),
	Field('FWHMG_rms', type = 'decimal' ),
	Field('FWHM_Mean', type = 'float' ),
	Field('FWHM_Min', type = 'float' ),
	Field('FWHM_Max', type = 'float' ),
	Field('MoffatBeta_Mean', type = 'float' ),
	Field('Ellipticity_Mean', type = 'float' ),
	Field('Asymmetry_Mean', type = 'float' ),
	Field('Chi2_Mean', type = 'float' ),
	Field('NStars_Loaded_Total', type = 'integer' , length = 11 ),
	Field('NStars_Accepted_Total', type = 'integer' , length = 11 ),
	Field('CRPIX1', type = 'float' ),
	Field('CRVAL1', type = 'double' ),
	Field('CRPIX2', type = 'float' ),
	Field('CRVAL2', type = 'double' ),
	Field('CD1_1', type = 'double' ),
	Field('CD1_2', type = 'double' ),
	Field('CD2_1', type = 'double' ),
	Field('CD2_2', type = 'double' ),
	Field('PIXSCALE', type = 'double' ),
	Field('Pipeline_ID', type = 'integer' , length = 3 ),
	Field('Release_ID', type = 'integer' , length = 3 ),
	Field('Filter_ID', type = 'integer' , length = 3 ),
	Field('is_valid', type = 'integer' , length = 3 ),
	Field('UserComment', type = 'text' ),
	Field('Quality_FLAG', type = 'integer' , length = 3 ),
	Field('DATASUM', type = 'integer' , length = 10 ),
	Field('CHECKSUM', type = 'string' , length = 16 ),
	Field('TimPrepSci', type = 'smallint' , length = 5 ),
	Field('TimCompCat', type = 'smallint' , length = 5 ),
	Field('TimAstrPho', type = 'smallint' , length = 5 ),
	Field('TimCombMed', type = 'smallint' , length = 5 ),
	Field('TimObjMask', type = 'smallint' , length = 5 ),
	Field('TimCombMea', type = 'smallint' , length = 5 ),
	Field('TimTilStat', type = 'smallint' , length = 5 ),
	Field('TimSingFCat', type = 'smallint' , length = 5 ),
	Field('TimDualFCat', type = 'smallint' , length = 5 ),
	Field('TimTilPSFAnaly', type = 'smallint' , length = 5 ),
	Field('TimMaskImp', type = 'smallint' , length = 5 ),
	Field('TimTotalTile', type = 'smallint' , length = 5 ),
	Field('Exit_Status', type = 'smallint' , length = 5 ),
	Field('BlockExec', type = 'integer' , length = 3 ),
	Field('TileType', type = 'integer' , length = 3 ),
	migrate = False)

db.define_table('t80tilestoload',
	Field('tile_ID', type = 'mediumint' , length = 8 ),
	Field('ref_tile_ID', type = 'mediumint' , length = 8 ),
	Field('single_load', type = 'integer' , length = 1 ),
	Field('dual_load', type = 'integer' , length = 1 ),
	Field('tile_update', type = 'integer' , length = 1 ),
	Field('ddbb', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('telescope',
	Field('Name', type = 'string' , length = 15 ),
	Field('Throughput', type = 'decimal' ),
	Field('Description', type = 'tinytext' ),
	Field('Path', type = 'string' , length = 15 ),
	migrate = False)

db.define_table('tile2hpix',
	Field('hpix', type = 'integer' , length = 11 ),
	Field('tile_id', type = 'integer' , length = 11 ),
	migrate = False)

db.define_table('tileastromsol_fields',
	Field('rc_id', type = 'mediumint' , length = 8 ),
	Field('tile_id', type = 'mediumint' , length = 8 ),
	Field('AstromSigma_Reference_1', type = 'float' ),
	Field('AstromSigma_Reference_2', type = 'float' ),
	Field('AstromSigma_Reference_HighSN_1', type = 'float' ),
	Field('AstromSigma_Reference_HighSN_2', type = 'float' ),
	Field('AstromOffset_Reference_1', type = 'float' ),
	Field('AstromOffset_Reference_2', type = 'float' ),
	Field('AstromOffset_Reference_HighSN_1', type = 'float' ),
	Field('AstromOffset_Reference_HighSN_2', type = 'float' ),
	Field('AstromCorr_Reference', type = 'float' ),
	Field('AstromCorr_Reference_HighSN', type = 'float' ),
	Field('Chi2_Reference', type = 'float' ),
	Field('Chi2_Reference_HighSN', type = 'float' ),
	Field('NDeg_Reference', type = 'integer' , length = 11 ),
	Field('NDeg_Reference_HighSN', type = 'integer' , length = 11 ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	migrate = False)

db.define_table('tileastromsol_groups',
	Field('tile_id', type = 'mediumint' , length = 8 ),
	Field('AstRef_Catalog', type = 'string' , length = 30 ),
	Field('AstRef_Band', type = 'string' , length = 20 ),
	Field('AstromNDets_Reference', type = 'integer' , length = 11 ),
	Field('AstromNDets_Reference_HighSN', type = 'float' ),
	Field('AstromSigma_Reference_1', type = 'float' ),
	Field('AstromSigma_Reference_2', type = 'float' ),
	Field('AstromSigma_Reference_HighSN_1', type = 'float' ),
	Field('AstromSigma_Reference_HighSN_2', type = 'float' ),
	Field('AstromOffset_Reference_1', type = 'float' ),
	Field('AstromOffset_Reference_2', type = 'float' ),
	Field('AstromOffset_Reference_HighSN_1', type = 'float' ),
	Field('AstromOffset_Reference_HighSN_2', type = 'float' ),
	Field('Chi2_Reference', type = 'float' ),
	Field('Chi2_Reference_HighSN', type = 'float' ),
	Field('AstromCorr_Reference', type = 'float' ),
	Field('AstromCorr_Reference_HighSN', type = 'float' ),
	Field('AstromNDets_Internal', type = 'integer' , length = 11 ),
	Field('AstromNDets_Internal_HighSN', type = 'integer' , length = 11 ),
	Field('AstromSigma_Internal_1', type = 'float' ),
	Field('AstromSigma_Internal_2', type = 'float' ),
	Field('AstromSigma_Internal_HighSN_1', type = 'float' ),
	Field('AstromSigma_Internal_HighSN_2', type = 'float' ),
	Field('Chi2_Internal', type = 'float' ),
	Field('Chi2_Internal_HighSN', type = 'float' ),
	Field('AstromCorr_Internal', type = 'float' ),
	Field('AstromCorr_Internal_HighSN', type = 'float' ),
	Field('DateInsert', type = 'date' ),
	Field('TimeInsert', type = 'time' ),
	migrate = False)

db.define_table('tilesphotozfiltersset',
	Field('set_ID', type = 'mediumint' , length = 8 ),
	Field('set_name', type = 'string' , length = 155 ),
	Field('description', type = 'text' ),
	migrate = False)

db.define_table('tilesphotoztoload',
	Field('tile_ID', type = 'mediumint' , length = 8 ),
	Field('software_ID', type = 'integer' , length = 11 ),
	Field('filters_set_ID', type = 'mediumint' , length = 8 ),
	Field('ddbb', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('tilestodelete',
	Field('tile_ID', type = 'mediumint' , length = 8 ),
	Field('ref_tile_ID', type = 'mediumint' , length = 8 ),
	Field('single_load', type = 'integer' , length = 1 ),
	Field('dual_load', type = 'integer' , length = 1 ),
	Field('ddbb', type = 'mediumint' , length = 8 ),
	migrate = False)

db.define_table('transparency',
	Field('rc_id', type = 'integer' , length = 10 ),
	Field('rc_ref_scamp_id', type = 'integer' , length = 10 ),
	Field('rc_ref_photint_id', type = 'integer' , length = 10 ),
	Field('tileinfo_id', type = 'integer' , length = 10 ),
	Field('updatemode', type = 'integer' , length = 3 ),
	Field('photsigma_internal', type = 'float' ),
	Field('photchi2_internal', type = 'float' ),
	Field('photndets_internal', type = 'mediumint' , length = 9 ),
	Field('reltransp_internal', type = 'float' ),
	Field('photsigma_internal_highsn', type = 'float' ),
	Field('photchi2_internal_highsn', type = 'float' ),
	Field('photndets_internal_highsn', type = 'mediumint' , length = 9 ),
	Field('low_SN_Threshold', type = 'float' ),
	Field('high_SN_Threshold', type = 'float' ),
	Field('TRANSP_wmean', type = 'float' ),
	Field('TRANSP_wstd', type = 'float' ),
	Field('TRANSP_median', type = 'float' ),
	Field('TRANSPncommonstars', type = 'mediumint' , length = 9 ),
	Field('TRANSP_minSN', type = 'float' ),
	Field('UPDATEDATE', type = 'timestamp' ),
	migrate = False)
